# Site settings
title: SuperCollider
description: >- # this means to ignore newlines in the following paragraph
  A platform for audio synthesis and algorithmic composition, used by musicians,
  artists and researchers working with sound.
description_bottom: >-
  Free and <a href="https://github.com/supercollider/supercollider">open source</a> software for Windows, MacOS and Linux.
favicon: assets/img/favicon.png

baseurl: ""
url: "https://supercollider.github.io"

# Website version
site_version: 0.1.3

# Build settings
sass:
  load_paths:
    - _sass
    - assets/css

# Plugins:
whitelist: []
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: sylhare/type-on-strap

# Theme settings
color_theme: auto
bootstrap: true
