# Site settings
title: SuperCollider
description: >- # this means to ignore newlines in the following paragraph
  An environment and programming language for real time audio synthesis and
  algorithmic composition.
favicon: assets/img/favicon.png
# Change this before merging
baseurl: /supercollider.github.io
url: "https://supercollider.github.io"

# Website version
site_version: 0.1.1

# Build settings
sass:
  load_paths:
    - _sass
    - assets/css

# Plugins:
whitelist: []
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: sylhare/type-on-strap

# Theme settings
color_theme: auto
bootstrap: true

# SC Version
github_url: "https://github.com/supercollider/supercollider"
current_version: 3.12.12
