name: Build website

on:
    pull_request: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Build
          uses: actions/jekyll-build-pages@v1
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            path: ./_site
            name: supercollider_website_{{ env.GITHUB_REF_NAME }}_{{ env.GITHUB_SHA }}
